chain-smoker/Marronnier

.gitignore
build.gradle
src/main/java/com/chainsmoker/marronnier/configuration/WebConfiguration.java
src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/EnumType/GenderEnum.java
src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/EnumType/PlatformEnum.java
src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/Member.java
src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/MemberEntity.java
src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/vo/AgeVO.java

---
* #1 
---
---
* 없음
---
---
* 맴버 컨텍스트의 맴버 엔티티를 생성하였습니다.
---
---
* 없음
---
---
* 없음

[#1] 맴버 엔티티 생성

---

build.gradle
src/main/java/com/chainsmoker/marronnier/configuration/DataBaseConfiguration.java
src/main/java/com/chainsmoker/marronnier/member/query/application/service/MemberQService.java
src/main/java/com/chainsmoker/marronnier/member/query/application/service/MemberQueryApplicationService.java
src/main/java/com/chainsmoker/marronnier/member/query/infra/repository/MemberMapper.java
src/main/java/com/chainsmoker/marronnier/member/query/infra/repository/MemberQInfraRepo.java
src/main/resources/config/mybatis-config.xml
src/main/resources/mapper/member/MemberMapper.xml

---
* #6 
---
---
* 없음
---
---
* 마이바티스 연결
* application.yml 파일의 경우 따로 공유할 예정
* `MemberMapper` 의 인터페이스를 어플리케이션에서 사용하는 구조 체크 필수
---
---
* 없음
---
---

[#6] MyBatis 연결 및 mapper 설정

---

src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/FeedQService.java
src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/Member.java
src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/vo/AgeRangeVO.java
src/main/java/com/chainsmoker/marronnier/member/command/domain/repository/MemberRepository.java
src/main/java/com/chainsmoker/marronnier/member/query/application/service/MemberService.java
src/main/java/com/chainsmoker/marronnier/member/query/domain/entity/vo/AgeRangeVO.java

---
* #19 
---
---
* 없음
---
---
* JPA를 통한 맴버 엔티티 생성
---
---
* 없음
---
---
* 없음

[#19] 맴버 엔티티 생성

---

src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/entity/Feed.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/repository/FeedRepo.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/repository/FeedQRepo.java
src/main/java/com/chainsmoker/marronnier/like/command/domain/aggregate/entity/Like.java

---
* 피드 엔티티 작성하고 JPA 로 인한 에러도 수정했습니다.
---
---
* JPA 선언으로 인해 오류 발생
---

피드 엔티티 작성 (#9)

---

src/main/java/com/chainsmoker/marronnier/apply/command/domain/aggregate/entity/Apply.java
src/main/java/com/chainsmoker/marronnier/apply/command/domain/aggregate/entity/ApplyEntity.java
src/main/java/com/chainsmoker/marronnier/apply/command/domain/aggregate/entity/EnumType/CategoryEnum.java
src/main/java/com/chainsmoker/marronnier/apply/query/application/controller/ApplyQController.java

---
* #12 
---
---
* 어떤 오류, 문제점이 발견되었는 지 작성한다.
*
---
---
* 주요 변경사항, 핵심 변경내용을 작성한다.
* 카테고리 enum 명칭 통일, @Setter 사용 수정, 회원 번호 필드 추가
---
---
*
---
---

[#12] 요청 엔티티 생성

---

src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/controller/CocktailRecipeController.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/aggregate/entity/CocktailRecipe.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/domain/entity/CocktailRecipeQuery.java
src/main/java/com/chainsmoker/marronnier/element/command/application/controller/ElementController.java
src/main/java/com/chainsmoker/marronnier/element/command/domain/aggregate/entity/Element.java
src/main/java/com/chainsmoker/marronnier/element/query/domain/entity/ElementQuery.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/application/controller/CocktailController.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/application/controller/ElementByRecipeController.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/domain/entity/ElementByRecipeQuery.java
src/main/resources/templates/cocktail/cocktailrecipe/cocktailrecipe.html
src/main/resources/templates/cocktail/element/element.html
src/main/resources/templates/cocktail/elementbyrecipe/elementbyrecipe.html
src/main/resources/templates/cocktail/regist.html

칵테일 등록 기능 시연을 위한 페이지 및 페이지 요청처리
---
* 칵테일 등록 기능 시연을 위한 페이지 구현
---
---
* 없음
---

[#20] 칵테일 등록 기능

---

src/main/java/com/chainsmoker/marronnier/feed/command/application/dto/FeedDTO.java
src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedService.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/repository/FeedReposiroty.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/entity/FeedQEntity.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/entity/QueryFeed.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/repository/FeedQRepo.java
src/main/java/com/chainsmoker/marronnier/feed/query/infra/repository/FeedMapper.java
src/main/java/com/chainsmoker/marronnier/feed/query/infra/repository/FeedQInfraRepo.java
src/main/resources/mapper/feed/FeedMapper.xml

---
* #40 
* #42 
* #9 
---
---
* 없음
---
---
* DTO생성했습니다.
---
---
* 없음
---
---
* 없음

피드 DTO 작성 [#40] , 피드 Repository 작성[#42], query Entity 작성[#9]

---

src/main/java/com/chainsmoker/marronnier/common/annotation/DomainService.java
src/main/java/com/chainsmoker/marronnier/configuration/DataBaseConfiguration.java
src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
src/main/java/com/chainsmoker/marronnier/member/command/application/service/RegistMemberService.java
src/main/java/com/chainsmoker/marronnier/member/query/application/service/FindMemberService.java

---
* #45 
---
---
* 없음
---
---
* 클래스 이름 수정
* 커스텀 도메인 서비스 어노테이션 설정 처리 한번 확인해주세요.
* MapperScan 어노테이션 파라미터를 통해 MyBatis mapper 스캔 최적화
---
---
---
* 없음

[Closes #45] Member 클래스 이름 수정 및 커스텀 DomainService 어노테이션 생성

---

src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/controller/RegistCocktailRecipeController.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/dto/RegistCocktailRecipeDTO.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/service/RegistCocktailRecipeService.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/aggregate/entity/CocktailRecipeEntity.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/repository/CocktailRecipeRepository.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/domain/entity/CocktailRecipeQueryEntity.java
src/main/java/com/chainsmoker/marronnier/member/command/application/controller/MemberController.java

---
* 의존성 주입 방법 변경 
* class name 수정
---
---
* 없음
---

[#46] 칵테일 등록 기능 서비스 수정

---

src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/CreateBasketController.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/DeleteBasketController.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/dto/BasketDTO.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/dto/CreateBasketDTO.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/dto/DeleteBasketDTO.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/service/DeleteBasketService.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/service/RegistBasketService.java
src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/entity/Basket.java
src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/vo/CockTailRecipeVO.java
src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/vo/MemberVO.java
src/main/java/com/chainsmoker/marronnier/basket/command/infra/repository/BasketRepository.java
src/main/java/com/chainsmoker/marronnier/basket/query/application/controller/FindBasketController.java
src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/QueryBasket.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/MemberRequestService.java
src/main/java/com/chainsmoker/marronnier/basket/query/infra/repository/BasketMapper.java
src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/MemberRequestService.java
src/main/java/com/chainsmoker/marronnier/common/annotation/InfraService.java
src/main/java/com/chainsmoker/marronnier/member/command/application/dto/CreateMemberDTO.java
src/main/java/com/chainsmoker/marronnier/member/query/application/dto/MemberCockTailBasketDTO.java
src/main/java/com/chainsmoker/marronnier/member/query/application/dto/MemberQDTO.java
src/main/java/com/chainsmoker/marronnier/member/query/infra/repository/MemberMapper.java
src/main/resources/mapper/basket/BasketMapper.xml
src/main/resources/templates/basket/add.html
src/main/resources/templates/basket/memberBaskets.html

---
* #49 
* #50 
---
---
* 없음
---
---
* 술바구니 엔티티의 관계 엔티티들을 VO로 설정 (`@Embeddable` , `@Embedded` 어노테이션 이용)
* 술바구니 어플리케이션 서비스에서 외부 어플리케이션 서비스를 이용할 때 interface를 통해 의존성 주입 (의존성 역전)
* 아래 코드처럼 술바구니 엔티티를 조회한 후 for문을 통해 각각의 맴버 정보와 칵테일조주법 정보를 조회하는 방식이 맞는지 강사님께 피드백 받아야 합니다.
~~~JAVA
public List<MemberCockTailBasketDTO> findByMemberId(long memberId) {
List<QueryBasket> baskets = basketMapper.findByMemberId(memberId);
List<MemberCockTailBasketDTO> memberCockTailBasketDTOList = new ArrayList<>();
for (QueryBasket basket : baskets) {
QueryMember member = memberRequestService.getMemberById(basket.getMemberId());
MemberCockTailBasketDTO memberCockTailBasketDTO = MemberCockTailBasketDTO
.builder()
.cockTailRecipeId(basket.getCockTailRecipeId())
.cockTailRecipeName(member.getName()) …

[Closes #49, Closes #50] 술바구니 엔티티 생성 및 생성,조회, 삭제 기능 구현

---

src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/CreateBasketController.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/DeleteBasketController.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/dto/BasketDTO.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/dto/CreateBasketDTO.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/dto/DeleteBasketDTO.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/service/DeleteBasketService.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/service/RegistBasketService.java
src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/entity/Basket.java
src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/vo/CockTailRecipeVO.java
src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/vo/MemberVO.java
src/main/java/com/chainsmoker/marronnier/basket/command/infra/repository/BasketRepository.java
src/main/java/com/chainsmoker/marronnier/basket/query/application/controller/FindBasketController.java
src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/QueryBasket.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/MemberRequestService.java
src/main/java/com/chainsmoker/marronnier/basket/query/infra/repository/BasketMapper.java
src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/MemberRequestService.java
src/main/java/com/chainsmoker/marronnier/common/annotation/InfraService.java
src/main/java/com/chainsmoker/marronnier/member/command/application/dto/CreateMemberDTO.java
src/main/java/com/chainsmoker/marronnier/member/query/application/dto/MemberCockTailBasketDTO.java
src/main/java/com/chainsmoker/marronnier/member/query/application/dto/MemberQDTO.java
src/main/java/com/chainsmoker/marronnier/member/query/infra/repository/MemberMapper.java
src/main/resources/mapper/basket/BasketMapper.xml
src/main/resources/templates/basket/add.html
src/main/resources/templates/basket/memberBaskets.html

---
* 사용자 세션 어트리부트 수정
---
---
* 세션 어트리부트 처리 수정
*
---
---
* 주요 변경사항, 핵심 변경내용을 작성한다.
*
---
---
* 없음
---
---
* 없음

[HOTFIX][MEMBER] 사용자 세션 어트리부트 수정

---

src/main/java/com/chainsmoker/marronnier/feed/command/application/controller/FeedController.java
src/main/java/com/chainsmoker/marronnier/feed/command/application/dto/CreateFeedDTO.java
src/main/java/com/chainsmoker/marronnier/feed/command/application/dto/FeedDTO.java
src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedInsertService.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/VO/CocktailRecipeVO.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/VO/MemberVO.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/entity/Feed.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/entity/FeedEntity.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/vo/FeedVO.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/service/FeedService.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/dto/CheckFeedDTO.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/dto/FeedQDTO.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/service/FeedQService.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/service/FindFeedService.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/entity/QueryFeed.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/repository/FeedM.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
src/main/java/com/chainsmoker/marronnier/feed/query/infra/repository/FeedMapper.java
src/main/resources/mapper/feed/FeedMapper.xml
src/main/resources/templates/feed/detail.html

---
* 이전 코드리뷰 피드백 수용
* #55 
* #40 
* #9 
---
---
* 없음
---
---
* @jiwon11 님이 이전에 피드백해 주신 부분 수정했습니다. (DTO 이름 수정, VO관련 부분)
---
---
* 없음
---
---
* 없음

피드 DTO 수정 [#40], query Entity 수정[#9], 피드 조회기능 구현[Closes #55]

---

src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/dto/RegistCocktailRecipeDTO.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/service/RegistCocktailRecipeService.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/aggregate/entity/CocktailRecipe.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/dto/FindCocktailRecipeDTO.java

---
* Builder사용 했기 때문
---
---
* 없음
---
---
* CocktailRecipe(Entity)
---
---
* 없음

[#57] Builder 어노테이션 지양 및 필요 필드에서만 Setter 사용

---

src/main/java/com/chainsmoker/marronnier/feed/command/application/controller/FeedController.java
src/main/java/com/chainsmoker/marronnier/feed/command/application/dto/UpdateFeedDTO.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/entity/Feed.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/service/FeedService.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/dto/CheckFeedDTO.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/service/FindFeedService.java
src/main/java/com/chainsmoker/marronnier/feed/query/infra/repository/FeedMapper.java
src/main/resources/mapper/feed/FeedMapper.xml
src/main/resources/templates/feed/detail.html
src/main/resources/templates/feed/update.html
src/main/resources/templates/feed/write.html

---
* #11 
* #42 
* FeedId->Id로 수정했습니다.
---
---
* 없음
---
---
* 전반적으로 피드에 필요한 정보가 더 많을 것 같은데 이에 대해서 최대한 빨리 상의해서 결정하는게 좋을 것 같습니다.
---
---
* 없음
---
---
* 없음

피드 수정 기능 [Closes #11] 및 피드백 수용(feedId->Id) [Closes #42],

---

settings.gradle
src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
src/main/java/com/chainsmoker/marronnier/configuration/auth/SessionUser.java
src/main/java/com/chainsmoker/marronnier/member/command/application/dto/CreateMemberDTO.java
src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/EnumType/Role.java
src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/Member.java
src/main/java/com/chainsmoker/marronnier/member/query/domain/entity/QueryMember.java

---
* #68 
---
---
* 없음
---
---
* 세션에 사용자 정보가 없을 경우, 카카오 로그인 페이지로 이동합니다.
* URL로 접근 시, 적합한 URL 매핑이 없을 경우 /home으로 이동합니다.
---
---
* 사용자 정보 없을 경우, 카카오 로그인 페이지로 이동
* 추후 홈화면으로 이동할 예정
---
---

[#68] 비로그인 시, 로그인 페이지로 이동

---

src/main/java/com/chainsmoker/marronnier/apply/command/application/controller/ApplyController.java
src/main/java/com/chainsmoker/marronnier/apply/command/application/controller/CreateApplyController.java
src/main/java/com/chainsmoker/marronnier/apply/command/application/dto/ApplyDTO.java
src/main/java/com/chainsmoker/marronnier/apply/command/application/dto/CreateApplyDTO.java
src/main/java/com/chainsmoker/marronnier/apply/command/application/service/ApplyService.java
src/main/java/com/chainsmoker/marronnier/apply/command/application/service/RegistApplyService.java
src/main/java/com/chainsmoker/marronnier/apply/command/domain/aggregate/entity/Apply.java
src/main/java/com/chainsmoker/marronnier/apply/command/infra/repository/ApplyInfraRepo.java
src/main/java/com/chainsmoker/marronnier/apply/command/infra/repository/ApplyRepository.java
src/main/java/com/chainsmoker/marronnier/apply/query/domain/entity/ApplyQEntity.java
src/main/resources/static/index.html
src/main/resources/templates/apply/add.html

---
* #34 
---
---
* 어떤 오류, 문제점이 발견되었는 지 작성한다.
---
---
* 요청글 작성 기능 구현
---
---
---
---

[#34] 요청글 작성 기능 구현

---

src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/VO/CocktailRecipeVO.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/VO/MemberVO.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/entity/Feed.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/entity/QueryFeed.java
src/main/java/com/chainsmoker/marronnier/like/command/domain/aggregate/entity/Like.java
src/main/java/com/chainsmoker/marronnier/like/command/domain/aggregate/vo/LikeVO.java
src/main/resources/mapper/feed/FeedMapper.xml
src/main/resources/templates/feed/feed.html

---
* #74 
---
---
* 없음
---
---
* 추가적으로 수정해야할 사항 있으면 알려주십시오
---
---
* 없음
---
---
* 없음

[Closes #74]코드 컨벤션 수정

---

src/main/java/com/chainsmoker/marronnier/admin/command/application/controller/CreateAdminController.java
src/main/java/com/chainsmoker/marronnier/admin/command/application/controller/MainAdminController.java
src/main/java/com/chainsmoker/marronnier/admin/command/application/dto/CreateAdminDTO.java
src/main/java/com/chainsmoker/marronnier/admin/command/application/service/RegistAdminService.java
src/main/java/com/chainsmoker/marronnier/admin/command/domain/aggragate/entity/Admin.java
src/main/java/com/chainsmoker/marronnier/admin/command/domain/aggragate/entity/EnumType/Role.java
src/main/java/com/chainsmoker/marronnier/admin/command/domain/aggragate/entity/vo/PasswordVO.java
src/main/java/com/chainsmoker/marronnier/admin/command/domain/repository/AdminRepository.java
src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
src/main/resources/templates/admin/home.html
src/main/resources/templates/admin/login.html
src/main/resources/templates/admin/regist.html

---
* #72 
---
---
* 없음
---
---
* 관리자 엔티티 추가
* 관리자 비밀번호의 경우 passwordVO를 통해 값 전달
---
---
* 없음
---
---
* 없음

[Closes #72] 어드민 엔티티 생성 및 어드민 가입 기능 구현

---

src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/service/FindCocktailRecipeService.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/infra/repository/FindCocktailRecipeMapper.java
src/main/java/com/chainsmoker/marronnier/element/query/application/controller/FindElementController.java
src/main/java/com/chainsmoker/marronnier/element/query/application/dto/FindElementDTO.java
src/main/java/com/chainsmoker/marronnier/element/query/application/service/FindElementService.java
src/main/java/com/chainsmoker/marronnier/element/query/infra/repository/FindElementMapper.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/domain/aggregate/entity/ElementByRecipe.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/controller/CocktailQController.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/controller/FindElementByRecipeController.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/dto/CocktailQDTO.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/dto/CocktailRecipeDTO.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/dto/FindElementByRecipeDTO.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/service/CocktailQService.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/service/FindElementByRecipeService.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/domain/entity/QueryElementByRecipe.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/domain/service/CocktailQService.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/domain/service/ElementRequestService.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/infra/repository/CocktailQInfraRepo.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/infra/repository/FindElementByRecipeMapper.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/infra/service/CocktailQInfraService.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/infra/service/ElementRequestService.java
src/main/resources/mapper/cocktail/FindCocktailRecipeMapper.xml
src/main/resources/mapper/cocktail/FindElementByRecipeMapper.xml
src/main/resources/mapper/cocktail/FindElementMapper.xml
src/main/resources/templates/cocktail/find/cocktailRecipe.html
src/main/resources/templates/cocktail/find/elementByrecipe.html

---
* 조주법별 재료 조회 기능 (술바구니 등록시 필요)
---
---
* 없음
---
---
* 다른 Package에서 domain service를 통해 메소드를 호출한 점
---
---
* 없음
---
---
* 각 local DB에 조주법별 재료, 재료, 칵테일 레시피가 등록되어야 테스트가 가능합니다.

[#60, #21] 칵테일 조회 기능

---

src/main/java/com/chainsmoker/marronnier/apply/query/application/controller/QueryApplyController.java
src/main/java/com/chainsmoker/marronnier/apply/query/application/dto/ApplyQDTO.java
src/main/java/com/chainsmoker/marronnier/apply/query/application/dto/QueryApplyDTO.java
src/main/java/com/chainsmoker/marronnier/apply/query/application/service/ApplyQService.java
src/main/java/com/chainsmoker/marronnier/apply/query/application/service/QueryApplyService.java
src/main/java/com/chainsmoker/marronnier/apply/query/domain/entity/QueryApply.java
src/main/java/com/chainsmoker/marronnier/apply/query/infra/repository/ApplyMapper.java
src/main/java/com/chainsmoker/marronnier/apply/query/infra/repository/ApplyQInfraRepo.java
src/main/java/com/chainsmoker/marronnier/apply/query/infra/repository/QueryApplyRepository.java
src/main/resources/mapper/apply/ApplyMapper.xml
src/main/resources/static/index.html
src/main/resources/templates/apply/find.html

#81
--- 
---
---
* 조회기능 구현 후 작성 기능이 안되는 문제가 발생하여 @GeneratedValue(strategy = GenerationType.AUTO) 변경
---
---
* service
* controller
---
---
<br>
---
---
* 카테고리에 빈 문자열 값이 전달될 때 예외처리 테스트 계획 예정.

[#81] 요청글 조회 기능 구현

---

src/main/java/com/chainsmoker/marronnier/feed/command/application/dto/FeedDTO.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/CheckLikeService.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/LikeService.java
src/main/java/com/chainsmoker/marronnier/feed/query/infra/service/CheckLikeService.java
src/main/java/com/chainsmoker/marronnier/like/command/application/controller/LikeController.java
src/main/java/com/chainsmoker/marronnier/like/command/application/controller/likecontroller.java
src/main/java/com/chainsmoker/marronnier/like/command/application/dto/LikeDTO.java
src/main/java/com/chainsmoker/marronnier/like/command/application/dto/likedto.java
src/main/java/com/chainsmoker/marronnier/like/command/application/service/PushLikeService.java
src/main/java/com/chainsmoker/marronnier/like/command/application/service/likeservice.java
src/main/java/com/chainsmoker/marronnier/like/command/domain/aggregate/entity/Like.java
src/main/java/com/chainsmoker/marronnier/like/command/domain/repository/LikeRepository.java
src/main/java/com/chainsmoker/marronnier/like/command/domain/repository/likerepository.java
src/main/java/com/chainsmoker/marronnier/like/query/domain/entity/QueryLike.java
src/main/java/com/chainsmoker/marronnier/like/query/domain/repository/LikeMapper.java
src/main/java/com/chainsmoker/marronnier/like/query/domain/service/FindLikeService.java
src/main/resources/mapper/like/LikeMapper.xml
src/main/resources/templates/feed/detail.html

---
* #14 
* #15 
---
---
* 없음
---
---
* 의존성 역전이 정상적으로 적용되었는지 확인부탁드립니다.
* 좋아요 누르기, 좋아요 취소, 좋아요 개수 보기 기능 추가했습니다.
---
---
* <img width="192" alt="image" src="https://github.com/chain-smoker/Marronnier/assets/74136791/52d71154-d361-45cc-b10c-ec0155c3a15f">
---
---
* 없음

[Closes #14] 좋아요 기능 추가 [Closes #15] 좋아요 취소 기능

---

src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/CocktailRecipeRequest.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/MemberRequest.java
src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/CocktailRecipeRequestService.java
src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/MemberRequestService.java
src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
src/main/java/com/chainsmoker/marronnier/main/query/application/controller/ErrorController.java
src/main/resources/templates/main/error.html

---
* #92
---
---
* 없음
---
---
* 사용자 정보가 없을 경우 인증 에러, 페이지 접근에 대한 권한이 없을 경우 인가 에러 입니다.
---
* 인증 실패 에러 페이지
* 인가 실패 에러 페이지
---
* 없음
---
---
* 없음

[Closes #92] 인증, 인가에 따른 에러 페이지 처리

---

src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/CocktailRecipeRequest.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/MemberRequest.java
src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/CocktailRecipeRequestService.java
src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/MemberRequestService.java

---
* #90 
---
---
* InfraService 에서 domain iterface를 implements 할 때 전체 패키지를 써야했던 문제를 수정했습니다.
---
---
* domain iterface의 이름을 infraService 클래스 이름과 동일하여 발생한 문제입니다. 따라서 domain iterface의 이름을 수정하였습니다.
---
---
*
---
---

[Closes #90] InfraService interface 클래스 전체 패키지 호출 수정

---

src/main/java/com/chainsmoker/marronnier/element/query/application/controller/SearchElementController.java
src/main/java/com/chainsmoker/marronnier/element/query/application/service/SearchElementService.java
src/main/java/com/chainsmoker/marronnier/element/query/infra/repository/SearchElementMapper.java
src/main/resources/mapper/cocktail/SearchElementMapper.xml
src/main/resources/templates/cocktail/searchMain.html

---
* #79 
---
---
* 없음
---
---
* axios를 활용한 비동기 검색 기능
---
---
* 재료 검색을 통한 비동기 검색 기능을 구현한 것으로 검색이나 혹은 비동기 처리를 하실 때 참고하시면 좋을 것 같습니다.
---

[#79] 칵테일 재료 검색 기능

---

src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/DeleteBasketController.java
src/main/java/com/chainsmoker/marronnier/basket/query/application/dto/MemberCockTailBasketDTO.java
src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
src/main/resources/templates/basket/memberBaskets.html

---
* #100 
---
---
* 없음
---
---
* 술바구니를 삭제할 경우 form으로 post method를 통해 데이터를 전달합니다.
~~~ HTML
<form action="/basket/delete" method="post">
<input th:value="${basket.getId()}" hidden="hidden" name="basketId">
<input th:value="${basket.getCockTailRecipeId()}" hidden="hidden" name="cockTailRecipeId">
<button type="submit">삭제</button>
</form>
~~~
---
---
* 없음
---
---
* 없음

[Closes #100] 술바구니 삭제 기능 구현

---

src/main/java/com/chainsmoker/marronnier/feed/command/application/controller/FeedController.java
src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedDeleteService.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/service/FeedService.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/service/FindFeedService.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
src/main/java/com/chainsmoker/marronnier/feed/query/infra/repository/FeedMapper.java
src/main/resources/mapper/feed/FeedMapper.xml
src/main/resources/templates/feed/detail.html

---
* #13 
---
---
*없음
---
---
* 삭제 기능 추가했습니다.
---
---
* 없음
---
---
* 없음

[Closes #13] 피드 삭제 기능 [Closes #40]

---

src/main/java/com/chainsmoker/marronnier/apply/command/application/controller/DeleteApplyController.java
src/main/java/com/chainsmoker/marronnier/apply/command/application/service/DeleteApplyService.java
src/main/resources/templates/apply/find.html

---
* #87 
---
---
* 어떤 오류, 문제점이 발견되었는 지 작성한다.
*
---
---
* 삭제 기능 추가하였고, 각 로그인 유저별 마이페이지에서만 자기 글 삭제할 수 있도록 뷰랑 연결해야 할 것 같습니다.
---
---
*
---
---

[#87] 요청 글 삭제 기능 추가

---

src/main/resources/templates/basket/memberBaskets.html

---
* #101 
---
---
* 없음
---
---
* 주요 변경사항, 핵심 변경내용을 작성한다.
*
---
---
*
---
---

[Closes #101] 술바구니 목록에서 피드 작성 페이지 연결

---

src/main/java/com/chainsmoker/marronnier/apply/command/application/controller/CreateApplyController.java
src/main/java/com/chainsmoker/marronnier/apply/command/application/controller/DeleteApplyController.java
src/main/java/com/chainsmoker/marronnier/apply/command/application/dto/CreateApplyDTO.java
src/main/java/com/chainsmoker/marronnier/main/query/application/controller/MainController.java
src/main/resources/templates/home.html

---
* #109 
---
---
---
---
* 사용자 입력 값 받는 방법 및 유저 정보 가져오는 방법을 수정 하였습니다.
```java
public String addApply(CreateApplyDTO createApplyDTO,
Authentication authentication) {
// 로그인된 사용자 id 가져오기
SessionUser sessionUser = (SessionUser) authentication.getPrincipal();
long requesterId = sessionUser.getId();
// 요청자 아이디 담기
createApplyDTO.setRequesterId(requesterId);
registApplyService.create(createApplyDTO);
return "redirect:/";
}
```
* 동적 메인 페이지를 연결하기 위해 컨트롤러 수정하였습니다.
```java
@Controller
@RequestMapping("/*")
public class MainController {
/* 동적 메인 페이지 연결*/
@GetMapping("")
public String home(Authentication authentication, Model model) {
model.addAttribute("member", null);
if(authentication != null) {
SessionUser member = (SessionUser) authentication.getPrincipal();
model.addAttribute("member", …
```

[#109] 요청 관련 컨트롤러 및 DTO 수정

---

src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/controller/RegistCocktailRecipeController.java
src/main/java/com/chainsmoker/marronnier/element/command/application/controller/RegistElementController.java
src/main/java/com/chainsmoker/marronnier/element/command/application/dto/RegistElementDTO.java
src/main/java/com/chainsmoker/marronnier/element/command/application/service/RegistElementService.java
src/main/java/com/chainsmoker/marronnier/element/command/domain/aggregate/EnumType/CategoryNameEnum.java
src/main/java/com/chainsmoker/marronnier/element/command/domain/aggregate/entity/Element.java
src/main/java/com/chainsmoker/marronnier/element/command/domain/repository/ElementRepository.java
src/main/resources/templates/cocktail/regist/element.html

---
* #20 
---
---
* 
---
---
* Element의 Regist 기능 구현 파트
* RegistElementService 파트
* 용민님은 RequestMapping 부분 수정 해주셔야 합니다.
---
---

[#20] Element(칵테일 재료) 등록 기능 구현

---

src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/controller/RegistCocktailRecipeController.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/controller/FindCocktailRecipeController.java
src/main/java/com/chainsmoker/marronnier/element/command/application/controller/RegistElementController.java
src/main/java/com/chainsmoker/marronnier/element/query/application/controller/FindElementController.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/controller/FindElementByRecipeController.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/domain/service/ElementRequest.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/infra/service/ElementRequestService.java
src/main/resources/templates/cocktail/findMain.html
src/main/resources/templates/cocktail/regist/cocktailRecipe.html
src/main/resources/templates/cocktail/registMain.html

---
* url 수정
* #112 
---
---
* 없음
---
---
* 없음
---

[#112] 칵테일 관련 기능 URL 수정

---

src/main/java/com/chainsmoker/marronnier/feed/command/application/controller/FeedController.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/CheckMemberNameService.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/LikeService.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
src/main/java/com/chainsmoker/marronnier/feed/query/infra/service/CheckMemberNameService.java
src/main/java/com/chainsmoker/marronnier/like/command/application/controller/LikeController.java
src/main/java/com/chainsmoker/marronnier/like/command/application/service/PushLikeService.java
src/main/java/com/chainsmoker/marronnier/like/query/domain/entity/QueryLike.java
src/main/resources/templates/feed/detail.html
src/main/resources/templates/feed/feed.html

---
* #124 
* #123 
---
---
* 좋아요를 누를때마다 새로운 뒤로가기 페이지가 생성되기 때문에 비동기로 처리가 필요
---
---
* 모달 기능 비동기로 처리
* 좋아요 기능 비동기 처리
---
---
* 
---
---
* 없음

[Closes #124] 좋아요 비동기 처리 [Closes #123] 게시글 페이지 비동기 처리

---

src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
src/main/java/com/chainsmoker/marronnier/configuration/auth/SessionUser.java
src/main/resources/templates/member/additional.html
src/main/resources/templates/member/profile.html

---
* #129 
---
---
* 어떤 오류, 문제점이 발견되었는 지 작성한다.
*
---
---
* 주요 변경사항, 핵심 변경내용을 작성한다.
*
---
---
*
---
---

[Closes #129] 사용자 인증 정보 프로필 이미지 추가

---

build.gradle
src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/CreateBasketController.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/DeleteBasketController.java
src/main/java/com/chainsmoker/marronnier/common/handler/OAuth2SuccessHandler.java
src/main/java/com/chainsmoker/marronnier/main/query/application/controller/MainController.java

---
* #136 
---
---
* 술바구니 ID 파라미터 pathVariable로 처리
---
---
* `/basket/add/{cockTailRecipeId}` 로 술바구니 ID 파라미터 pathVariable로 처리
---
---
*
---
---
* 없음

[Closes #136] 술바구니 ID 파라미터를 통한 추가

---

src/main/java/com/chainsmoker/marronnier/apply/command/application/controller/CreateApplyController.java
src/main/resources/templates/apply/add.html

---
* #138 
---
---
* 없음
---
---
* 아래 스크린샷과 같이 템플릿 적용하였습니다.
* 글을 작성한 후 사용자의 프로필 페이지로 redirect 되게 수정하였습니다.
* 헤더에 사용자의 정보를 보여줘야 하기 때문에 컨트롤러에서 getMapping 메소드에 authorization에서 인증사용자의 정보를 불러오도록 수정하였습니다.
---
---
* 없음
---
---
* 없음

[Closes #138] 요청글 작성 페이지 템플릿 적용

---

src/main/resources/templates/member/additional.html
src/main/resources/templates/member/profile.html

---
* #140 
---
---
* 없음
---
---
* 카카오 우편번호 API를 통해 사용자의 주소지를 받아옵니다.
---
---
* 없음
---
---
* 없음

[Closes #140] 카카오 우편본호 입력을 통한 맴버 주소지 입력

---

src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/CreateBasketController.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/controller/RecommandController.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/controller/FindElementByRecipeController.java
src/main/java/com/chainsmoker/marronnier/main/query/application/controller/MainController.java
src/main/resources/templates/cocktail/find/elementByrecipe.html
src/main/resources/templates/cocktail/question/first.html
src/main/resources/templates/cocktail/question/second.html
src/main/resources/templates/cocktail/question/third.html
src/main/resources/templates/cocktail/resultCocktail.html
src/main/resources/templates/home.html

---
* #118 
* template 적용
---
---
* 없음
---
---
* <img width="501" alt="image" src="https://github.com/chain-smoker/Marronnier/assets/136034038/99027a9a-22ac-4295-84a3-cda3289dacfa">
* 
---

[#118] 칵테일 추천 기능

---

src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/CreateBasketController.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/DeleteBasketController.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/dto/DeleteBasketDTO.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/service/DeleteBasketService.java
src/main/java/com/chainsmoker/marronnier/basket/command/application/service/RegistBasketService.java
src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/entity/Basket.java
src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/entity/BasketCompositeKey.java
src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/vo/CockTailRecipeVO.java
src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/vo/MemberVO.java
src/main/java/com/chainsmoker/marronnier/basket/command/domain/repository/BasketRepository.java
src/main/java/com/chainsmoker/marronnier/basket/query/application/dto/MemberCockTailBasketDTO.java
src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/QueryBasket.java
src/main/resources/mapper/basket/BasketMapper.xml
src/main/resources/mapper/cocktail/RecommandMapper.xml
src/main/resources/templates/member/additional.html
src/main/resources/templates/member/profile.html
src/test/java/com/chainsmoker/marronnier/CompositeKeyBasketTests.java

---
* #144
---
---
* 같은 칵테일을 추가했을 때 같은 데이터가 새로 추가되는 문제를 해결했습니다.
---
---
* 술바구니를 복합키로 처리하였습니다. 
* 테스트를 통해 복합키를 통한 술바구니 생성 여부 확인하였습니다.
---
---
* 없음
---
---
* 없음

[Closes #144] 술바구니 복합키로 처리

---

src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/dto/RegistCocktailRecipeDTO.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/aggregate/entity/CocktailRecipe.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/domain/entity/QueryCocktailRecipe.java

---
* #151 
---
---
* 없음
---
---
* 칵테일 recipe 컬럼 추가
---
---
* 없음
---

[#151] 칵테일 조주법 recipe 컬럼추가

---

src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/service/RegistCocktailRecipeService.java
src/main/resources/mapper/basket/BasketMapper.xml
src/main/resources/templates/member/profile.html

---
* #156 
---
---
* 없음
---
---
* 술바구니를 추가 날짜 기준으로 변경하였습니다
---
---
* 없음
---
---
* 없음

[Closes #156] 술바구니 정렬 기준 변경

---

src/main/java/com/chainsmoker/marronnier/photo/command/application/controller/InsertPhotoController.java
src/main/java/com/chainsmoker/marronnier/photo/command/application/dto/PhotoDTO.java
src/main/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoService.java
src/main/java/com/chainsmoker/marronnier/photo/command/domain/aggregate/entity/EnumType/PhotoCategory.java
src/main/java/com/chainsmoker/marronnier/photo/command/domain/aggregate/entity/Photo.java
src/main/java/com/chainsmoker/marronnier/photo/command/domain/aggregate/entity/PhotoCategory.java
src/main/java/com/chainsmoker/marronnier/photo/command/domain/aggregate/entity/PhotoCompositeKey.java
src/main/java/com/chainsmoker/marronnier/photo/command/domain/aggregate/vo/OriginVO.java
src/main/java/com/chainsmoker/marronnier/photo/command/domain/repository/PhotoRepository.java
src/main/resources/templates/photo/write.html
src/test/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoServiceTest.java

---
* #94 
---
---
---
---
```java
String originPhotoName = photo.getOriginalFilename();
if (originPhotoName != null) {
/* 확장자 명으로 분리 */
String ext = originPhotoName.substring(originPhotoName.lastIndexOf("."));
String savedName = UUID.randomUUID().toString().replace("-", "") + ext;
String path = "/photo" + "/" + savedName;
try {
photo.transferTo(new File(photoPath + "/" + savedName));
PhotoDTO photoinfo = new PhotoDTO(originPhotoName, savedName, category, path);
insertPhotoService.insertPhoto(photoinfo);
} catch (IOException e) {
Files.delete(Path.of(path));
}
}
```
* 확장자 명으로 오리지널 파일명을 분리해서 새로운 파일 이름을 적용 시킨후 DTO에 담아 서비스로 넘깁니다.
* 칵테일 조주법, 재료, 피드 enum 타입 보시고 값 넘길 때 적용하시면 될 것 같습니다.
---
---
---
---

[#94] 사진 업로드

---

src/main/java/com/chainsmoker/marronnier/basket/query/application/controller/FindBasketController.java
src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/BasketCompositeKey.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/QueryBasket.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/vo/CockTailRecipeVO.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/vo/MemberVO.java
src/main/java/com/chainsmoker/marronnier/basket/query/domain/repository/FindBasketRepository.java
src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
src/main/java/com/chainsmoker/marronnier/member/query/application/controller/MemberProfileController.java
src/main/java/com/chainsmoker/marronnier/member/query/application/dto/FindBasketsPaginationDTO.java
src/main/java/com/chainsmoker/marronnier/member/query/infra/service/RequestMemberBasketService.java
src/main/resources/static/css/custom.css
src/main/resources/templates/basket/memberBaskets.html
src/main/resources/templates/member/profile.html
src/test/java/com/chainsmoker/marronnier/basket/PaginationBasketTests.java

---
* #158 
---
---
* 없음
---
---
* 술바구니를 페이지 처리하였습니다.
---
---
* 없음
---
---
* 페이지 번호를 통해 사용자의 술바구니 목록 페이징 조회 테스트를 수행하였습니다.

[Closes #158] 술바구니 페이징 처리

---

src/main/java/com/chainsmoker/marronnier/feed/command/domain/repository/FeedRepo.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/dto/CheckFeedDTO.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/service/FindFeedService.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
src/main/java/com/chainsmoker/marronnier/feed/query/infra/repository/FeedMapper.java
src/main/java/com/chainsmoker/marronnier/like/command/domain/service/likeservice.java
src/main/java/com/chainsmoker/marronnier/like/command/infra/service/likeservice.java
src/main/resources/templates/feed/feed.html
src/main/resources/templates/feed/update.html
src/main/resources/templates/feed/write.html

---
* #160 
* #161 
---
---
* 없음
---
---
* 템플릿 적용 확인 및 queryFeedDTO 수정
---
---
* 
---
---
* 없음

[Closes #160] queryfeedDTO필요정보 추가 [Closes #161] 피드 수정 및 작성페이지 템플릿 적용

---

src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/controller/RecommandController.java
src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/service/RecommandService.java
src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/controller/FindElementByRecipeController.java
src/main/java/com/chainsmoker/marronnier/main/query/application/controller/MainController.java
src/main/resources/templates/cocktail/find/elementByrecipe.html
src/main/resources/templates/cocktail/question/first.html
src/main/resources/templates/cocktail/question/second.html
src/main/resources/templates/cocktail/question/third.html
src/main/resources/templates/cocktail/resultCocktail.html
src/main/resources/templates/home.html

---
* #163 
---
---
* 없음
---
---
* first.html 
*  Controller
* second.html
* Controller
* third.html
* Controller
* 코드를 보면 요청 방식이 좀 일관되지 않은 것을 볼 수 있습니다.
* 일부러 이렇게 작성한 이유는 공부하면서 여러가지 방법을 통해 GET요청을 이용한 데이터 전송이 가능하다는 것을 보여주기 위해서입니다.
* 첫번째는 넘길 정보가 하나이기 때문에 controller에서 PathVariable을 통해 데이터를 전송한 것을 볼 수 있습니다.
* 두번째부터는 두개 이상의 값을 넘겨야 했는데 이를 name을 매핑시켜서 받는 방법과 Map형태로 받을 수 있습니다.
---
---
* 최종적으로 User에 의해 선택된 recommandInfo로 칵테일 조주법이 올바르게 조회되는지 확인해야함.

[#163] 칵테일 추천 기능 요청방식 수정

---

src/main/resources/templates/admin/login.html
src/main/resources/templates/admin/regist.html

---
* #165 
---
---
* 없음
---
---
* 관리자의 로그인 및 회원가입 페이지에 템플릿을 적용하였습니다.
---
- 관리자 로그인 페이지
-관리자 회원가입 페이지
---
* 없음
---
---
* 없음

[Closes #165] 관리자 로그인 회원가입 템플릿 적용

---

src/main/resources/templates/apply/detail.html
src/main/resources/templates/apply/find.html

---
* #171 
*  요청글 상세페이지 탬플릿 적용했습니다.
---
---
---
---
---
---
---
---

[Closes #171] 상세페이지 Bootstrap 적용

---

src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/dto/CheckFeedDTO.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
src/main/resources/templates/feed/feed.html

---
* #174 
---
---
* 없음
---
---
* 피드 detail을 확인할 때 작성자의 프로필이 보이도록 수정
* 피드 작성자가 아닐 경우 modal footer자체가 안보이도록 수정
---
---
* 
---
---
* 없음

[Closes #174] 피드 작성자 프로필이 보이도록 하기

---

src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/dto/CheckFeedDTO.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
src/main/java/com/chainsmoker/marronnier/like/query/domain/repository/LikeMapper.java
src/main/java/com/chainsmoker/marronnier/like/query/domain/service/FindLikeService.java
src/main/resources/mapper/like/LikeMapper.xml
src/main/resources/templates/feed/feed.html
src/test/java/com/chainsmoker/marronnier/like/query/domain/service/LikeServiceTests.java

---
* #167 
---
---
* 없음
---
---
* memberId를 통해 좋아요를 누른 feedId를 반환
---
---
* 
---
---
* ![image](https://github.com/chain-smoker/Marronnier/assets/74136791/11a1d7fc-af5a-47f7-9ff4-960b161eb93a)

[Closes #167] 사용자 ID를 통한 종아요 누른 피드 조회

---

src/main/java/com/chainsmoker/marronnier/basket/query/domain/repository/FindBasketRepository.java
src/main/java/com/chainsmoker/marronnier/member/query/application/controller/MemberProfileController.java
src/main/java/com/chainsmoker/marronnier/member/query/application/service/FindMemberLikedFeedService.java
src/main/java/com/chainsmoker/marronnier/member/query/application/service/FindMemberService.java
src/main/java/com/chainsmoker/marronnier/member/query/application/service/FindMemberWroteFeedService.java
src/main/java/com/chainsmoker/marronnier/member/query/domain/entity/aggregate/QueryMember.java
src/main/java/com/chainsmoker/marronnier/member/query/domain/entity/aggregate/vo/AgeRangeVO.java
src/main/java/com/chainsmoker/marronnier/member/query/domain/repository/MemberMapper.java
src/main/java/com/chainsmoker/marronnier/member/query/domain/service/RequestMemberLikedFeed.java
src/main/java/com/chainsmoker/marronnier/member/query/domain/service/RequestMemberWroteFeed.java
src/main/java/com/chainsmoker/marronnier/member/query/infra/service/RequestMemberLikedFeedService.java
src/main/java/com/chainsmoker/marronnier/member/query/infra/service/RequestMemberWroteFeedService.java
src/main/resources/mapper/member/MemberMapper.xml
src/main/resources/static/css/custom.css
src/main/resources/templates/member/profile.html
src/test/java/com/chainsmoker/marronnier/member/GetMemberFeedTests.java

---
* #95 
* #167 
---
---
* 없음
---
---
* 사용자의 프로필에서 사용자가 작성한 피드 목록을 보여줍니다.
* 사용자의 프로필에서 사용자가 좋아요한 피드 목록을 보여줍니다.
---
---
* 목록 탭의 경우 비동기 방식으로 처리하지 않고 쿼리 파라미터를 통해 처리하였습니다.
```
// profile.html
<th:block th:if="${feedCategory == 'wrote'}">
<li class="nav-item">
<a class="nav-link active" aria-current="page" href="/member/profile?feed=wrote">내가 쓴 피드</a>
</li>
<li class="nav-item">
<a class="nav-link" href="/member/profile?feed=like">좋아요한 피드</a>
</li>
</th:block>
<th:block th:if="${feedCategory == 'like'}">
<li class="nav-item">
<a class="nav-link" href="/member/profile?feed=wrote">내가 쓴 피드</a>
</li>
<li class="nav-item">
<a class="nav-link active" aria-current="page" href="/member/profile?feed=like">좋아요한 피드</a>
</li>
</th:block>
```
```
// MemberProfileController
@GetMapping("/profile")
public …
```

[Closes #95, Closes #167] 사용자의 프로필에서 좋아요 또는 작성한 피드 목록 조회

---

src/main/resources/templates/member/profile.html

---
* 사용자 프로필 드로다운 적용 안되면 문제를 해결
---
---
* 사용자 프로필 드로다운 적용 안되면 문제를 해결하였습니다.
*
---
---
* script 코드 추가
```
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
```
---
---
* 없음
---
---
* 없음

[!hotfix] 사용자 프로필 드롭다운 적용 안되면 문제 해결

---

src/main/resources/templates/member/profile.html

---
* #191 
* #193 
---
---
* 없음
---
---
* 사용자 프로필의 피드들의 사진을 적용하였습니다.
---
---
* 없음
---
---
* 없음

[#191] 사용자 프로필 작성한 피드 및 좋아요한 피드 사진 적용

---

src/main/java/com/chainsmoker/marronnier/feed/command/application/controller/FeedController.java
src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedDeleteService.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/service/DeleteLikeService.java
src/main/java/com/chainsmoker/marronnier/feed/command/infra/service/DeleteLikeService.java
src/main/java/com/chainsmoker/marronnier/like/command/application/service/PushLikeService.java
src/main/java/com/chainsmoker/marronnier/like/command/domain/repository/LikeRepository.java

---
* 피드를 삭제하면 좋아요도 삭제되는 기능 추가.
---
---
* 없음
---
---
* 피드를 삭제하면 좋아요도 사라져요!
---
---
* 없음
---
---
* 없음

[Closes #200]피드를 삭제하면 좋아요도 삭제되는 기능 추가

---

src/test/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoServiceTest.java

---
* #205 
---
---
* 없음
---
---
* `MockMVC` 클래스와 `MockMultipartFile` 를 통해 이미지 압로드 테스트 코드를 작성하였습니다.
---
---
* 없음
---
---
* 이미지 업로드 테스트 완료

[Closes #205] 이미지 생성 테스트 코드 작성

---

src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
src/main/resources/templates/common/modal.html
src/main/resources/templates/feed/update.html

---
* #213 
---
---
* 없음
---
---
* 피드에서 신고 버튼 및 신고 모달 디자인 수정했습니다.
* 신고 버튼은 피드 작성자에게는 보이지 않습니다.
---
---
* 
---
---
* 없음

[Closes #213] 피드 신고 디자인 수정

---

src/main/java/com/chainsmoker/marronnier/feed/command/application/controller/FeedController.java
src/main/java/com/chainsmoker/marronnier/feed/command/application/dto/UpdateFeedDTO.java
src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedPhotoService.java
src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedUpdateService.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/entity/Feed.java
src/main/java/com/chainsmoker/marronnier/feed/command/domain/service/FeedService.java
src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
src/main/resources/templates/common/feed.html
src/main/resources/templates/feed/update.html
src/main/resources/templates/feed/write.html

---
* #218 
---
---
* 없음
---
---
* 파드 수정시 사진을 수정할 수 있도록 수정했습니다.
---
---
* 없음
---
---
* 없음

 피드 사진 수정 기능 추가

---

src/main/resources/templates/apply/add.html
src/main/resources/templates/home.html
src/main/resources/templates/member/additional.html

---
* #220 
---
---
* 없음
---
---
* 없음
---
---
* 
---
---

[Closes #220] 디자인 수정

---

src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java

---
* #223 
---
---
* 없음
---
---
* 칵테일 사진을  전부 넣어주지 않으면 nullpointer 에러 발생할 수 있으니 주의해주세요
---
---
* 없음
---
---
* 없음.

[Closes #223] 피드 작성시 사진을 넣지 않았을 때 dafault값 처리

---

src/main/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoService.java
src/test/java/com/chainsmoker/marronnier/photo/command/application/controller/UpdatePhotoTest.java

---
* hotfix
---
---
* GitHub action에서 수행하는 테스트 코드에서 파일을 경로를 못차는 문제
---
---
* 없음
---
---
* 없음
---
---
* GitHub action 모든 테스트 pass 완료

[!HotFix] 테스트 사진 저장 폴더 위치 출력

---

src/test/java/com/chainsmoker/marronnier/feed/command/controller/service/FeedApplicationServiceTests.java

---
* #226 
---
---
* 없음
---
---
* 피드 테스트 코드 작성
---
---
* 
---
---
* 피드 작성
* 피드 수정

[Closes #226] 피드 테스트코드 작성

---

src/main/resources/templates/cocktail/find/elementByrecipe.html
src/main/resources/templates/cocktail/question/first.html
src/main/resources/templates/cocktail/question/second.html
src/main/resources/templates/cocktail/question/third.html
src/main/resources/templates/cocktail/resultCocktail.html
src/main/resources/templates/main/search.html

[#116] 통합 검색

---

src/main/resources/templates/apply/add.html

[#229] 요청글 페이지 template수정

---

src/main/resources/templates/cocktail/question/second.html
src/main/resources/templates/main/search.html

---
* #232 
---
---
* 없음
---
---
---

[Closes #232] 칵테일 추천받기 멘트 수정

---

src/main/java/com/chainsmoker/marronnier/apply/command/domain/aggregate/entity/EnumType/CategoryEnum.java
src/main/resources/templates/apply/add.html

---
* #234 
---
---
---
---
---
---
---
---

[Closes #234] 카테고리 피드백 항목 추가
